version: "3.1"
   
services:  
  db:
    container_name: uk_db
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=post
      - POSTGRES_USER=post
      - POSTGRES_PASSWORD=post
    volumes:
      - ./postgress/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always

  web:
    container_name: uk_dj
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
