# Generated by Django 2.2.17 on 2021-04-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Доступ к админке'),
            preserve_default=False,
        ),
    ]
