# Generated by Django 2.2.17 on 2021-04-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0003_auto_20210406_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
