# Generated by Django 2.2.17 on 2021-04-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0004_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Доступ к админке'),
        ),
    ]
