# Generated by Django 2.2.17 on 2021-04-06 02:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('add_number', models.PositiveIntegerField(verbose_name='add_number')),
                ('sq_appart', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='sq_appart')),
                ('num_owner', models.PositiveIntegerField(default=0, verbose_name='num_owner')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='period')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='payer')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='services')),
                ('unit', models.CharField(max_length=32, verbose_name='unit')),
                ('standart', models.DecimalField(blank=True, decimal_places=4, default='', max_digits=8, verbose_name='standart')),
                ('rate', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='rate')),
                ('factor', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='factor')),
                ('const', models.BooleanField(db_index=True, default=True, verbose_name='const_payments')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='services_activ')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name_category')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='category_is_active')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128, verbose_name='street')),
            ],
        ),
        migrations.CreateModel(
            name='UK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='services')),
                ('requisites', models.TextField(verbose_name='requisites')),
                ('web_addr', models.CharField(max_length=128, verbose_name='services')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_account', models.CharField(max_length=32, unique=True, verbose_name='personal_account')),
                ('name', models.CharField(max_length=128, verbose_name='user_name')),
                ('type_electric_meter', models.CharField(choices=[('1', 'однотарифный'), ('2', 'двухтарифный')], max_length=1, verbose_name='counter_type')),
                ('appartament', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.Appartament')),
                ('invoice', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='VariablePayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='period')),
                ('service', models.CharField(max_length=128, verbose_name='name_service')),
                ('unit', models.CharField(max_length=32, verbose_name='unit')),
                ('standart', models.DecimalField(blank=True, decimal_places=4, default='125', max_digits=8, verbose_name='standart')),
                ('rate', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='rate')),
                ('accured', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='rate')),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='volume')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='factor')),
                ('subsidies', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='subsidies')),
                ('privileges', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='privileges')),
                ('recalculations', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='privileges')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='privileges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.User')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.PositiveIntegerField(default=0, verbose_name='Sale')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.User')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.ServicesCategory'),
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.PositiveIntegerField(default=0, verbose_name='Sale')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.User')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('add_number', models.PositiveIntegerField(verbose_name='number')),
                ('sq_home', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='sq_home')),
                ('category_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.ServicesCategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.City')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Street')),
                ('uk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.UK')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='period')),
                ('hist_col_water', models.PositiveIntegerField(verbose_name='hist_col_water')),
                ('hist_hot_water', models.PositiveIntegerField(verbose_name='hist_hot_water')),
                ('hist_electric_day', models.PositiveIntegerField(verbose_name='hist_electric_day')),
                ('hist_electric_night', models.PositiveIntegerField(verbose_name='hist_electric_night')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.User')),
            ],
            options={
                'ordering': ('-period',),
            },
        ),
        migrations.CreateModel(
            name='CurrentCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_water', models.PositiveIntegerField(null=True, verbose_name='col_water')),
                ('hot_water', models.PositiveIntegerField(null=True, verbose_name='hot_water')),
                ('electric_day', models.PositiveIntegerField(null=True, verbose_name='electric_day')),
                ('electric_night', models.PositiveIntegerField(null=True, verbose_name='electric_day')),
                ('electric_sungle', models.PositiveIntegerField(blank=True, default='', null=True, verbose_name='electric_single')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.User')),
            ],
        ),
        migrations.CreateModel(
            name='ConstantPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.User')),
            ],
        ),
        migrations.AddField(
            model_name='appartament',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.House'),
        ),
    ]
