# Generated by Django 2.2.17 on 2021-04-01 09:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='category_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.ServicesCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='const',
            field=models.BooleanField(db_index=True, default=True, verbose_name='const_payments'),
        ),
        migrations.CreateModel(
            name='VariablePayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='period')),
                ('service', models.CharField(max_length=128, verbose_name='name_service')),
                ('price', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='rate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.User')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='period')),
                ('hist_col_water', models.PositiveIntegerField(verbose_name='hist_col_water')),
                ('hist_hot_water', models.PositiveIntegerField(verbose_name='hist_hot_water')),
                ('hist_electric_day', models.PositiveIntegerField(verbose_name='hist_electric_day')),
                ('hist_electric_night', models.PositiveIntegerField(verbose_name='hist_electric_night')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.User')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_water', models.PositiveIntegerField(null=True, verbose_name='col_water')),
                ('hot_water', models.PositiveIntegerField(null=True, verbose_name='hot_water')),
                ('electric_day', models.PositiveIntegerField(null=True, verbose_name='electric_day')),
                ('electric_night', models.PositiveIntegerField(null=True, verbose_name='electric_day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.User')),
            ],
        ),
        migrations.CreateModel(
            name='ConstantPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.User')),
            ],
        ),
    ]
